<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
    <PackageReference Include="Razorpay" Version="3.3.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="UglyToad.PdfPig" Version="0.1.9-alpha001-patch1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediScope.Common\MediScope.Common.csproj" />
    <ProjectReference Include="..\MediScope.Data\MediScope.Data.csproj" />
  </ItemGroup>

</Project>